"""Shared constants for RADS tokenization and ARC-AGI action IDs."""

from __future__ import annotations

ARC_AGI_2_COLORS = 10
ARC_AGI_3_COLORS = 16

MASK_TOKEN_ID = 16
SEP_TOKEN_ID = 17
VOCAB_SIZE = 18

MAX_GRID_SIZE = 64
TRM_STATIC_BATCH_SIZE = 64

RESET_ACTION = 0
ACTION1 = 1
ACTION2 = 2
ACTION3 = 3
ACTION4 = 4
ACTION5 = 5
ACTION6 = 6
ACTION7 = 7
SIMPLE_ACTIONS = tuple(range(ACTION1, ACTION7 + 1))
ALL_ACTIONS = (RESET_ACTION,) + SIMPLE_ACTIONS
